# Generated by Django 2.1.7 on 2019-03-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='google_url',
            new_name='url',
        ),
    ]
