# Generated by Django 2.1.7 on 2019-03-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
