# Generated by Django 2.1.7 on 2019-03-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_savedrecipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='recipes',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
