# Generated by Django 2.1.7 on 2019-03-17 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0007_auto_20190317_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('describtion', models.CharField(max_length=100)),
                ('fanciness', models.CharField(max_length=100)),
                ('firstDate', models.CharField(max_length=100)),
                ('lazyNight', models.CharField(max_length=100)),
                ('difficulty', models.CharField(max_length=100)),
                ('dishType', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('veggie', models.CharField(max_length=100)),
                ('overall', models.CharField(max_length=100)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SavedRecipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
