# Generated by Django 2.1.7 on 2019-03-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='describtion',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='dishType',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='fanciness',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='firstDate',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='lazyNight',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='price',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='veggie',
        ),
    ]
